version: "2"
services:
  nook-weather:
    build: ./
    container_name: "nook-weather"
    restart: unless-stopped
    ports:
      - "3099:3099"
    environment:
      - EMAIL="test@testing.test"
      - ZIP_CODE=YOUR_ZIP_CODE
    logging:
      options:
        max-size: 1m
        max-file: "3"
